# Generated by Django 4.2.3 on 2023-07-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_contacts_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
